### ISSUE TITLE
Overview / Nodes / Memory Info is not right

### ISSUE THREAD

**Issue by erylee** [emqtt/emqttd_dashboard#13]
![mem](https://cloud.githubusercontent.com/assets/11869/9148706/f3cccd20-3db9-11e5-89c3-8c1d514961d5.png)

**Comment by erylee** [comment]
1. data is not right
2. should display 20MB, 2.5GB...

**Comment by huangdan** [comment]
emqttd_vm:get_memory()   total_memory  used_memory
