### ISSUE TITLE
'Sessions' page exception

### ISSUE THREAD

**Issue by erylee** [emqtt/emqttd_dashboard#19]
=ERROR REPORT==== 11-Aug-2015::14:40:21 ===
Error in process <0.287.0> on node 'emqttd@127.0.0.1' with exit value: {{badmatch,[]},[{emqttd_dashboard,session_table,1,[{file,"src/emqttd_dashboard.erl"},{line,231}]},{emqttd_dashboard,'-api/2-fun-2-',1,[{file,"src/emqttd_dashboard.erl"},{line,125}]},{lists,map,2,[{file,"lists.erl"},{line,1237}]},{emqttd_dashboard...

=ERROR REPORT==== 11-Aug-2015::14:40:21 ===
Error in process <0.282.0> on node 'emqttd@127.0.0.1' with exit value: {{badmatch,[]},[{emqttd_dashboard,session_table,1,[{file,"src/emqttd_dashboard.erl"},{line,231}]},{emqttd_dashboard,'-api/2-fun-2-',1,[{file,"src/emqttd_dashboard.erl"},{line,125}]},{lists,map,2,[{file,"lists.erl"},{line,1237}]},{emqttd_dashboard...

**Comment by huangdan** [comment]
topic  qos return []  
the default loading loading
