### ISSUE TITLE
{undef,[{emqttd_vm,get_system_info,[check_io]

### ISSUE THREAD

**Issue by erylee** [emqtt/emqttd_dashboard#22]
Error in process <0.276.0> on node 'emqttd@127.0.0.1' with exit value: {function_clause,[{emqttd_dashboard,'-api/2-lc$^1/1-6-',[{badrpc,{'EXIT',{undef,[{emqttd_vm,get_system_info,[check_io],[]},{rpc,local_call,3,[{file,"rpc.erl"},{line,329}]},{emqttd_dashboard,'-api/2-fun-0-',1,[{file,"src/e...

**Comment by huangdan** [comment]
merge dev-hd branch emqttd_vm.erl
