### ISSUE TITLE
emqttd_dashboard:session_table/1 exception

### ISSUE THREAD

**Issue by erylee** [emqtt/emqttd_dashboard#26]
Reason:     {{badmatch,[{<<"topic/#">>,1},
                             {<<"client1/100/2164022716">>,0}]},
                  [{emqttd_dashboard,session_table,1,
                                     [{file,"src/emqttd_dashboard.erl"},
                                      {line,248}]},
                   {emqttd_dashboard,'-api/2-fun-2-',1,
                                     [{file,"src/emqttd_dashboard.erl"},
                                      {line,127}]},
                   {lists,map,2,[{file,"lists.erl"},{line,1237}]},
                   {emqttd_dashboard,api,2,
                                     [{file,"src/emqttd_dashboard.erl"},
                                      {line,126}]},
                   {mochiweb_http,headers,6,
                                  [{file,"src/mochiweb_http.erl"},
                                   {line,76}]}]}

**Comment by huangdan** [comment]
remove subscriptions
