### ISSUE TITLE
compile warnings

### ISSUE THREAD

**Issue by erylee** [emqtt/emqttd_dashboard#29]
/Users/feng/Releases/emqttd/plugins/emqttd_dashboard/src/emqttd_dashboard_app.erl:27: Warning: function close_listener/1 is unused
Compiled src/emqttd_dashboard_app.erl
/Users/feng/Releases/emqttd/plugins/emqttd_dashboard/src/emqttd_dashboard_users.erl:107: Warning: variable 'User' is unused
/Users/feng/Releases/emqttd/plugins/emqttd_dashboard/src/emqttd_dashboard_users.erl:120: Warning: variable 'User' is unused

**Comment by erylee** [comment]
/Users/feng/Releases/emqttd/plugins/emqttd_dashboard/src/emqttd_dashboard_app.erl:27: Warning: function close_listener/1 is unused
Compiled src/emqttd_dashboard_app.erl
/Users/feng/Releases/emqttd/plugins/emqttd_dashboard/src/emqttd_dashboard_users.erl:107: Warning: variable 'User' is unused
/Users/feng/Releases/emqttd/plugins/emqttd_dashboard/src/emqttd_dashboard_users.erl:120: Warning: variable 'User' is unused

**Comment by huangdan** [comment]
emqttd_dashoboard_users.erl
