### ISSUE TITLE
admin don't limit when login in

### ISSUE THREAD

**Issue by guidao** [emqtt/emqttd_dashboard#34]
admin don't limit times when login in and emqttd_dashboard_users:check/1 use atom(UserName). The may be make many atom when someone repeat login in that use different username.
you can use erlang:list_to_existing_atom/1 replace it.

**Comment by erylee** [comment]
@guidao, Yes! I found this issue yesterday, and grep 'list_to_atom' in the whole project and submit an issue: https://github.com/emqtt/emqttd/issues/284

I will notify author @huangdan to fix it. Thanks:)

**Comment by huangdan** [comment]
the username data type is atom .Atom data type have count limit.
now,username data type is binnary
