### ISSUE TITLE
Dashboard cannot read Broker system values

### ISSUE THREAD

**Issue by elisiariocouto** [emqtt/emqttd_dashboard#47]
Hello,

The dashboard cannot read the values for System Name, Version, Uptime and System Time on the Broker row on the overview page. Can you guide me how to troubleshoot this?

<img width="1221" alt="screenshot" src="https://cloud.githubusercontent.com/assets/818914/13854369/0cb72120-ec63-11e5-86db-82f5741aa374.png">

**Comment by huangdan** [comment]
@elisiariocouto 
i confirm with you the problem，you say the problem is just open overview interface  no value Or still has no value？
if it's the first case may the EMQTTD broker has just started, overview Page subscribe system topic takes time

**Comment by huangdan** [comment]
and browser does not support websocket?

**Comment by elisiariocouto** [comment]
Hi @huangdan,

Yes, the browser supports WebSockets and I can connect to the websocket port. I understand that sometimes the data takes some time to load, but this is not the case. The other data loads almost instantly.

**Comment by elisiariocouto** [comment]
I figured it out. The dashboard tries to connect with the user "dashboard" and no password. I have username authentication enabled and, because of this, the login fails. We should be able to modify this on the dashboard.

**Comment by huangdan** [comment]
v1.1 repair
