### ISSUE TITLE
Changing dashboard credentials for username authentication

### ISSUE THREAD

**Issue by tercanfurkan** [emqtt/emqttd_dashboard#56]
Currently dashboard client uses `{username: "dashboard", password: ""}` for authentication. This is hard-coded in:
https://github.com/emqtt/emqttd_dashboard/blob/master/priv%2Fwww%2Fassets%2Fjs%2Fdashboard-custom.js#L450

This should be possible to change using a config file or from the dashboard web interface.

**Comment by elisiariocouto** [comment]
Issue #47 is related. Apparently fixed in v1.1.

**Comment by emqplus** [comment]
./bin/emqttd_ctl commands:
```
admins add <Admin> <Password>
admins del <Admin>
admins passwd <Admin> <Password>
```

**Comment by tercanfurkan** [comment]
Is this for the admin login or for the dashboard client authentication to emqtt?

**Comment by huangdan** [comment]
This is just a dashboard manage users
